---
#headless
apiVersion: v1
kind: Service
metadata:
  name: application-dns-internal
spec:
  ports:
    - name: management
      port: 8558
      protocol: TCP
      targetPort: 8558
    - name: remoting
      port: 2551
      protocol: TCP
      targetPort: 2551
  selector:
    app: ms-arditi-cluster
  clusterIP: None
  publishNotReadyAddresses: true
#headless
---
#public
kind: Service
apiVersion: v1
metadata:
  name: ms-arditi-cluster
spec:
  type: NodePort
  selector:
    app: ms-arditi-cluster
  ports:  
    - protocol: TCP
      name: api
      port: 8080
      targetPort: api
#public
---